import type { Dimension, Checked, Score, BlockingItem, Summary } from "../types/domain";

export const itemId = (dimId: string, level: number, index: number): string => `${dimId}-${level}-${index}`;

export function dimScore(dim: Dimension, checked: Checked): Score {
  const per = dim.levels.map((items, li) => {
    const done = items.filter((_, ii) => checked[itemId(dim.id, li, ii)]).length;
    return { done, total: items.length };
  });
  let attained = 0;
  for (let l = 0; l < 4; l++) {
    if (per[l].done === per[l].total) attained = l + 1;
    else break;
  }
  let partial = 0;
  if (attained < 4) {
    const nx = per[attained];
    partial = nx.total ? nx.done / nx.total : 0;
  }
  return { per, attained, partial, value: attained + partial * 0.999 };
}

export function blockingItems(dim: Dimension, score: Score, checked: Checked): BlockingItem[] {
  const nl = score.attained;
  if (nl >= dim.levels.length) return [];
  return dim.levels[nl]
    .map((it, ii) => ({ ...it, ii }))
    .filter((it) => !checked[itemId(dim.id, nl, it.ii)]);
}

export function buildSummary(
  dimensions: Dimension[],
  levelNames: string[],
  scores: Score[],
  checked: Checked
): Summary {
  return {
    tool: "Agentic Development Maturity Matrix",
    date: new Date().toISOString().slice(0, 10),
    overall: +(scores.reduce((a, s) => a + s.attained + s.partial, 0) / dimensions.length).toFixed(2),
    dimensions: dimensions.map((d, i) => ({
      id: d.id,
      name: d.name,
      attainedLevel: scores[i].attained,
      levels: scores[i].per.map((p, li) => ({
        level: li + 1,
        name: levelNames[li],
        ticked: p.done,
        total: p.total,
        items: d.levels[li].map((it, ii) => ({ text: it.title, done: !!checked[itemId(d.id, li, ii)] })),
      })),
    })),
  };
}

export function buildMarkdownSummary(summary: Summary): string {
  let md = `# Agentic Development Maturity — ${summary.date}\n\n**Overall: ${summary.overall.toFixed(
    1
  )} / 4.0**\n\n| Dimension | Level | L1 | L2 | L3 | L4 |\n|---|---|---|---|---|---|\n`;
  summary.dimensions.forEach((x) => {
    md += `| ${x.name} | L${x.attainedLevel} | ${x.levels.map((l) => `${l.ticked}/${l.total}`).join(" | ")} |\n`;
  });
  md += `\n## Next steps (weakest first)\n`;
  summary.dimensions
    .filter((x) => x.attainedLevel < 4)
    .sort((a, b) => {
      const va = a.attainedLevel + (a.levels[a.attainedLevel]?.ticked || 0) / (a.levels[a.attainedLevel]?.total || 1);
      const vb = b.attainedLevel + (b.levels[b.attainedLevel]?.ticked || 0) / (b.levels[b.attainedLevel]?.total || 1);
      return va - vb;
    })
    .forEach((x) => {
      const nl = x.levels[x.attainedLevel];
      md += `\n### ${x.name} — to reach L${x.attainedLevel + 1} (${nl.name})\n`;
      nl.items.filter((it) => !it.done).forEach((it) => {
        md += `- [ ] ${it.text}\n`;
      });
    });
  md += `\nGenerated by the Agentic Development Maturity Matrix.\n`;
  return md;
}
